- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ download_dir }}"
    - "{{ release_dir }}"
    - "{{ backup_dir }}"

#- name: Backup Old war file
  #command: cp /usr/local/tomcat/webapps/*.war {{ backup_dir }}/

- name: Download war file from artifactory
  get_url:
    url: "{{ download_url }}"
    dest: "{{ artifact_file }}"
    username: admin
    password: exaze
    mode: 0644

- name: Stop tomcat
  service:
    name: tomcat
    state: stopped

  #- name: Delete old war
  #command: rm -rf /home/apache-tomcat-9.0.37/webapps/abc*

- name: Copy the war file
  copy:
    src: "{{ artifact_file }}"
    dest: /usr/share/tomcat/webapps
    remote_src: yes

- name: restart tomcat
  service:
    name: tomcat
    state: restarted